.\" Hey, Emacs!  This is an -*- nroff -*- source file.
.TH CHIARK\-CRYPTDISK\-MAKE\-KEY 8 "9th July 2008" "Greenend" "chiark utilities"
.SH NAME
chiark\-cryptdisk\-make\-key \- create crypto keyset
.SH SYNOPSIS
.BR chiark\-cryptdisk\-make\-key 
.SH DESCRIPTION
.B chiark-cryptdisk-make-key
is a tool for WRITEME

.SH SECURITY
WRITEME
.SH EXIT STATUS
.TP
.B 0
All went well and there were no warnings.
.TP
any other
WRITEME
.SH FILES
.TP
.B WRITEME
Default configuration file.  (Override with
.BR -C .)

.SH BUGS
Probably some.

.SH AUTHOR
This manual page was written by Ross Youger <ryounger@chiark.greenend.org.uk>
in 2008, but may be used by anyone.
.SH COPYRIGHT
.B chiark-cryptdisk-make-key
was written by Ian Jackson <ian@chiark.greenend.org.uk> in XXX.

The chiark-cryptdisk package is free software; you can redistribute it
and/or modify it under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 3, or (at
your option) any later version.

This is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
details.

You should have received a copy of the GNU General Public License along
with this program; if not, consult the Free Software Foundation's
website at www.fsf.org, or the GNU Project website at www.gnu.org.
.SH SEE ALSO
.BR chiark-cryptdisk-initialise-disc "(8), "
