#!/bin/bash -e
. /usr/lib/chiark-cryptdisk/functions

ro=-r
case "$1" in
--rw) ro=''; shift;;
esac
test $# = 0 || fail "usage: .../examine [--rw]"

do_identify
do_dmsetup $keyid
if [ "x${FSCK_ON_MOUNT}" = "xy" ] || [ "x${FSCK_ON_MOUNT}" = "xyes" ]; then
	do_fsck
fi
do_mount $ro
echo 'mounted.'
egrep . /dev/null $mnt/disk-id ||:
