#!/bin/sh
set -e

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
export PATH

host=`hostname`

cd /usr/lib/crypt-disk-backup
with-lock-ex -f lock bash -xec '
 savelog -c 7 logfile
 result=successful
 bash -xec "
  ./examine --rw
  ./main
  ./unmount
 " >logfile 2>&1 || result=FAILED
 mail -s "${host} backup $result" ${MAILTO} <logfile
 ./unmount
'
