#!/bin/bash
set -e
. /usr/lib/chiark-cryptdisk/functions
test $# = 0 || fail "usage: .../make-key"

generate_thing () {
	our_dd if=/dev/urandom bs=1 count=16 of=${KEYS}/$1.bin
	hexdump -e '16 1 "%02x" "\n"' <${KEYS}/$1.bin >${KEYS}/$1.hex
	thing_hex=`cat ${KEYS}/$1.hex`
}

if ! test -f ${KEYS}/identifier-magic.bin; then
	generate_thing identifier-magic
	echo "identifier $thing_hex chosen"
else
	identifier=`cat ${KEYS}/identifier-magic.hex`
	echo "identifier $identifier already set"
fi

generate_thing new-key-id 
keyid=$thing_hex

our_dd if=/dev/urandom bs=1 count=16 of=${KEYS}/new-key-id.bin
bin2hex ${KEYS}/new-key-id
keyid_hex=`cat ${KEYS}/new-key-id.hex`

mkdir -p -m700 ${KEYS}
our_dd if=/dev/urandom bs=1 count=32 of=${KEYS}/$keyid_hex

rm -f ${KEYS}/current-key-id.hex
mv ${KEYS}/new-key-id.bin ${KEYS}/current-key-id.bin
mv ${KEYS}/new-key-id.hex ${KEYS}/current-key-id.hex

echo "key $keyid_hex generated"
