#!/bin/sh
set -e

MODULE=shift

if ! lsmod | egrep '^'${MODULE}' ' >/dev/null \
    && [ x$NO_CRYPTDISK_MOUNT = x ]; then
	modprobe $MODULE
	sleep 1
fi

find /sys/devices -path '*/driver' -lname '*'${MODULE}'*' -print \
 | perl -pe 's,/driver$,,' \
 | xargs -I @ find @ -path '*/host*/target*/*:*:*:*/block:*' -print \
 | perl -pe 's,.*:,,'
