#!/bin/bash
set -e
export NO_CRYPTDISK_MOUNT=1
. /usr/lib/chiark-cryptdisk/functions >/dev/null
test $# = 0 || fail "usage: .../unmount"
carelessly undo_mount
carelessly undo_dmsetup
if mountpoint -q $mnt; then
	df -P $mnt >&2
	echo "device is mounted!" >&2
	exit 2
fi
if dmsetup ls | grep "^$mapname[ 	]" >/dev/null; then
	dmsetup info $mapname >&2
	echo "devmapper table $mapname still present!" >&2
	exit 1
fi


if test ${NO_RMMOD} = 0; then
	if lsmod | grep -F $MODULE >/dev/null; then
		rmmod $MODULE 
	fi
fi

/sbin/hdparm -qf /dev/$dev

if [ "x${SLEEP_DRIVE}" = "xy" ] || [ "x${SLEEP_DRIVE}" = "xyes" ]; then
	/sbin/hdparm -qY /dev/$dev
fi

echo ok

